// WiseExportExcelAddin.idl : WiseExportExcelAddin的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(WiseExportExcelAddin.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(FBAF994B-EC27-44A0-951C-67BE9F8A5C3C),
	pointer_default(unique)
]
interface IWiseExportExcel : IUnknown{
};
[
	uuid(C6B03EEC-1058-4358-B148-124BA259ABC4),
	version(1.0),
]
library WiseExportExcelAddinLib
{
	importlib("stdole2.tlb");
	[
		uuid(B6204179-EEEC-4F2A-A6AD-B53725170450)		
	]
	coclass WiseExportExcel
	{
		[default] interface IWiseExportExcel;
	};
};

